# Generated by Django 5.2.1 on 2025-05-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('hospitalization_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospitalization_StartDate', models.DateField()),
                ('hospitalization_room', models.SmallIntegerField()),
                ('hospitalization_EndDate', models.DateField()),
            ],
            options={
                'db_table': 'hospitalization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncludesConducting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Includes_conducting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncludesReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Includes_reception',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalBook',
            fields=[
                ('MedicalBook_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'medicalBook',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalBookContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MedicalBook_id', models.IntegerField()),
                ('MedicalBook_content_notes', models.TextField(blank=True, max_length=1500, null=True)),
            ],
            options={
                'db_table': 'medicalBook_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalStaff',
            fields=[
                ('medical_staff_name', models.CharField(max_length=150)),
                ('medical_staff_birthday', models.DateField()),
                ('medical_staff_gender', models.CharField(max_length=3)),
                ('medical_staff_post', models.CharField(max_length=100)),
                ('medical_staff_specialisation', models.CharField(max_length=100)),
                ('medical_staff_departament', models.CharField(max_length=100)),
                ('medical_staff_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'medical_staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_id', models.AutoField(primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=150)),
                ('medication_dose', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'medication',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicationDispensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_dispensing_date', models.DateField()),
                ('medication_dispensing_status', models.CharField(max_length=20)),
                ('medication_dispensing_dose', models.IntegerField(blank=True, null=True)),
                ('medication_dispensing_com', models.TextField(blank=True, max_length=1500, null=True)),
            ],
            options={
                'db_table': 'medication_dispensing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Procedures',
            fields=[
                ('procedures_id', models.AutoField(primary_key=True, serialize=False)),
                ('procedures_name', models.CharField(max_length=100)),
                ('procedures_duration', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'procedures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProceduresExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedures_execution_date', models.DateField()),
                ('procedures_execution_status', models.CharField(max_length=20)),
                ('procedures_execution_duration', models.IntegerField(blank=True, null=True)),
                ('procedures_execution_com', models.TextField(blank=True, max_length=1500, null=True)),
            ],
            options={
                'db_table': 'procedures_execution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('purpose_id', models.AutoField(primary_key=True, serialize=False)),
                ('purpose_StartDate', models.DateField()),
                ('purpose_duration', models.SmallIntegerField()),
                ('purpose_status', models.CharField(max_length=100)),
                ('purpose_diagnosis', models.TextField(max_length=1500)),
            ],
            options={
                'db_table': 'purpose',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_birthday', models.DateField()),
                ('patient_gender', models.CharField(max_length=10)),
                ('patient_photo', models.ImageField(blank=True, null=True, upload_to='patient_photos/')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
