# Generated by Django 5.2.1 on 2025-06-01 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('hospitalization_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospitalization_startdate', models.DateField()),
                ('hospitalization_room', models.SmallIntegerField()),
                ('hospitalization_enddate', models.DateField()),
            ],
            options={
                'db_table': 'hospitalization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Procedures',
            fields=[
                ('procedures_id', models.AutoField(primary_key=True, serialize=False)),
                ('procedures_name', models.CharField(max_length=100)),
                ('procedures_duration', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'procedures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_id', models.AutoField(primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=150)),
                ('medication_dose', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'medication',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalBook',
            fields=[
                ('medicalbook_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'medicalbook',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalBookContent',
            fields=[
                ('medical_book_content_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicalbook_id', models.IntegerField()),
                ('medical_book_content_notes', models.TextField(blank=True, max_length=1500, null=True)),
            ],
            options={
                'db_table': 'medical_book_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicationDispensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_dispensing_date', models.DateField()),
                ('medication_dispensing_status', models.CharField(max_length=20)),
                ('medication_dispensing_dose', models.IntegerField(blank=True, null=True)),
                ('medication_dispensing_com', models.TextField(blank=True, max_length=1500, null=True)),
            ],
            options={
                'db_table': 'medication_dispensing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('purpose_id', models.AutoField(primary_key=True, serialize=False)),
                ('purpose_startdate', models.DateField()),
                ('purpose_duration', models.SmallIntegerField()),
                ('purpose_status', models.CharField(max_length=100)),
                ('purpose_diagnosis', models.TextField(max_length=1500)),
            ],
            options={
                'db_table': 'purpose',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_birthday', models.DateField()),
                ('patient_gender', models.CharField(max_length=10)),
                ('patient_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('patient_height', models.IntegerField()),
                ('patient_blood_type', models.CharField(max_length=3)),
                ('patient_photo', models.ImageField(blank=True, default='no-photo.webp', null=True, upload_to='patient_photos/')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='IncludesConducting',
            fields=[
                ('procedures', models.ForeignKey(db_column='procedures_id', on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='main.procedures')),
            ],
            options={
                'db_table': 'includes_conducting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncludesReception',
            fields=[
                ('medication', models.ForeignKey(db_column='medication_id', on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='main.medication')),
            ],
            options={
                'db_table': 'includes_reception',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalStaff',
            fields=[
                ('medical_staff_name', models.CharField(max_length=150)),
                ('medical_staff_birthday', models.DateField()),
                ('medical_staff_gender', models.CharField(max_length=3)),
                ('medical_staff_post', models.CharField(max_length=100)),
                ('medical_staff_specialisation', models.CharField(max_length=100)),
                ('medical_staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medical_staff',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProceduresExecution',
            fields=[
                ('procedures_execution_id', models.AutoField(primary_key=True, serialize=False)),
                ('procedures_execution_date', models.DateField(verbose_name='Дата выполнения процедуры')),
                ('procedures_execution_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Продолжительность')),
                ('procedures_execution_status', models.CharField(max_length=20, verbose_name='Статус выполнения процедуры')),
                ('procedures_execution_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('medical_staff', models.ForeignKey(db_column='medical_staff_id', on_delete=django.db.models.deletion.RESTRICT, to='main.medicalstaff')),
                ('procedures', models.ForeignKey(db_column='procedures_id', on_delete=django.db.models.deletion.RESTRICT, to='main.procedures')),
            ],
            options={
                'verbose_name': 'Выполнение процедуры',
                'verbose_name_plural': 'Выполнения процедур',
                'db_table': 'procedures_execution',
                'managed': True,
                'unique_together': {('procedures', 'medical_staff')},
            },
        ),
    ]
