# Generated by Django 5.2.1 on 2025-05-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalization',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='includesconducting',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='includesreception',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='medicalbook',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='medicalbookcontent',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='medicalstaff',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='medicationdispensing',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='procedures',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='proceduresexecution',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='purpose',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
