# Generated by Django 5.2.1 on 2025-06-02 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalstaff',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='proceduresexecution',
            options={'managed': False, 'verbose_name': 'Выполнение процедуры', 'verbose_name_plural': 'Выполнения процедур'},
        ),
    ]
